### PR TITLE
Compatibility with BTrees 4

### PR DESCRIPTION
**Pull request by davisagli**
Use an empty string instead of None because we can no longer use None as a BTree key.

Sorry for mixing this with cleanup. Look at 	bf2cfe8 for the substantive commit; the rest are cleanup.

Note: This is not backwards compatible without a migration; hence the bump in major version number. Before merging this we should either add a Plone upgrade step or make sure existing Plone versions are using a branch.

### CODE REVIEW

**Comment by jensens** [comment]
LGTM

**Comment by jensens** [comment]
With the latest release of BTrees 4.4.0 https://pypi.python.org/pypi/BTrees/4.4.0 the None problem was addressed and solved.

**Comment by jensens** [comment]
BTrees 4.4.0 works with Plone 5.1 coredev w/o any problems as it seems. 
https://github.com/plone/buildout.coredev/pull/291

**Comment by davisagli** [comment]
Yeah, this isn't needed now -- but rather than closing the PR I will rebase so that it includes just the cleanup commits.

**Pull request closed without merging**
